name: Build & Push WebApp Blazor Server

on:
  push:
    branches:
      - '**'
  pull_request: 
    branches:
      - main
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout du code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Log in to Docker Hub
      - name: Log in to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DH_USER }}
          password: ${{ secrets.DH_TOKEN }}

      # 3. Extraire infos Git
      - name: Extract Git metadata
        id: vars
        run: |
          echo "sha_short=${GITHUB_SHA::7}" >> $GITHUB_ENV
          echo "ref_name=${GITHUB_REF_NAME}" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image for pull request
        if: github.event_name == 'pull_request'
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64
          push: false
          tags: 1fini/tennisscore-webapp:pr-${{ env.sha_short }}

      - name: Build and push multi-arch Docker image
        if: github.event_name != 'pull_request'
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ secrets.DH_USER }}/tennisscore-webapp:latest
            ${{ secrets.DH_USER }}/tennisscore-webapp:${{ env.sha_short }}

      - name: Tag release image
        if: github.event_name == 'release'
        run: |
          docker buildx imagetools create \
            -t ${{ secrets.DH_USER }}/tennisscore-webapp:${{ env.ref_name }} \
            ${{ secrets.DH_USER }}/tennisscore-webapp:${{ env.sha_short }}
